#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/sbin/quectel-timesync

start_service() {
    config_load 'quectel-timesync'

    local enabled
    local path
    local interval

    # Get values from /etc/config/quectel-timesync section 'main'
    config_get_bool enabled main enabled 0
    config_get path main path
    config_get interval main interval 3600

    # Stop if not enabled
    [ "$enabled" -eq 1 ] || return 1

    # Stop if path is missing
    if [ -z "$path" ]; then
        logger -t quectel-timesync "ERROR: Device path not set"
        return 1
    fi

    # Start the daemon
    procd_open_instance
    # command: /usr/sbin/quectel-timesync -d 3600 -p /dev/ttyUSB2
    procd_set_param command "$PROG" -d "$interval" -p "$path"
    
    # Ensure it stays running
    procd_set_param respawn
    
    # Capture output to logread for debugging
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_close_instance
}
