#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

# This allows LuCI to trigger a restart when you click "Save & Apply"
CONF="quectel-timesync"
PROG="/usr/sbin/quectel-timesync"

start_instance() {
    local section="$1"
    local enabled
    local path
    local interval

    config_get_bool enabled "$section" 'enabled' 0
    config_get path "$section" 'path'
    config_get interval "$section" 'interval' 3600

    # If this specific section is disabled, do nothing
    [ "$enabled" -eq 1 ] || return 0

    if [ -z "$path" ]; then
        logger -t quectel-timesync "Section $section: path not set"
        return 0
    fi

    procd_open_instance "$section"
    procd_set_param command "$PROG" -d "$interval" -p "$path"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start_service() {
    config_load "$CONF"
    config_foreach start_instance 'quectel-timesync'
}

service_triggers() {
    # This tells procd to restart the service whenever the config file changes
    procd_add_reload_trigger "$CONF"
}
